#!/bin/bash

code-server --install-extension ms-python.python
code-server --install-extension lextudio.restructuredtext
code-server --install-extension trond-snekvik.simple-rst


# Install the VS code proxy
pip install -e.