#!/bin/bash

code-server --install-extension ms-python.python
code-server --install-extension lextudio.restructuredtext
code-server --install-extension trond-snekvik.simple-rst

npx puppeteer install chrome

echo 'export PUPPETEER_EXECUTABLE_PATH=$(find $HOME/.cache/puppeteer/chrome/ -name chrome | head -n1)' >> ~/.bashrc
echo 'export PUPPETEER_SKIP_DOWNLOAD=true' >> ~/.bashrc

# Disable sandbox for Puppeteer/Decktape
echo 'export PUPPETEER_ARGS="--no-sandbox --disable-setuid-sandbox"' >> ~/.bashrc

npm install -g decktape

# Install the VS code proxy
pip install -e.