#!/bin/bash

# Provide the VS Code Marketplace gallery endpoint (EXTENSIONS_GALLERY)
export EXTENSIONS_GALLERY='{"serviceUrl":"https://marketplace.visualstudio.com/_apis/public/gallery","itemUrl":"https://marketplace.visualstudio.com/items"}'

code-server --install-extension ms-python.python
code-server --install-extension lextudio.restructuredtext
code-server --install-extension trond-snekvik.simple-rst
code-server --install-extension GitHub.copilot
code-server --install-extension GitHub.copilot-chat
code-server --install-extension quarto.quarto
code-server --install-extension ms-python.vscode-pylance

npx puppeteer install chrome

echo 'export PUPPETEER_EXECUTABLE_PATH=$(find $HOME/.cache/puppeteer/chrome/linux-* -name chrome | head -n1)' >> ~/.bashrc
echo 'export PUPPETEER_SKIP_DOWNLOAD=true' >> ~/.bashrc

# Disable sandbox for Puppeteer/Decktape
echo 'export PUPPETEER_ARGS="--no-sandbox --disable-setuid-sandbox"' >> ~/.bashrc

npm install -g decktape

# Install the VS code proxy
pip install -e.