# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

revealjs:
	$(SPHINXBUILD) -b revealjs $(SOURCEDIR) $(BUILDDIR)/revealjs
	@echo
	@echo "Build finished. The Reveal.js presentation is in $(BUILDDIR)/revealjs."

autobuild:
	sphinx-autobuild -b revealjs $(SOURCEDIR) $(BUILDDIR)/revealjs
	@echo
	@echo "Live server started. Open http://127.0.0.1:8000/ to view your Reveal.js presentation."


pdfslides:
	mkdir -p $(BUILDDIR)/latex
	decktape reveal $(BUILDDIR)/revealjs/index.html $(BUILDDIR)/latex/slides.pdf --chrome-arg="--no-sandbox"
	@echo
	@echo "Build finished. The pdf slides are in $(BUILDDIR)/latex/slides.pdf."

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
